update action

diff --git a/.github/workflows/postman-tests.yml b/.github/workflows/postman-tests.yml
--- a/.github/workflows/postman-tests.yml
+++ b/.github/workflows/postman-tests.yml
@@ -27,13 +27,16 @@ jobs:
         sudo lsof -ti :3000 | xargs --no-run-if-empty kill -9
 
     - name: Run YAML server in background
-      run: |
-        nohup npm run turn-on-api &
-        echo "Waiting for server to start..."
-        sleep 5
-        curl -f http://localhost:3000 || { echo "Server failed to start!"; exit 1; }
-        echo "Server is up and running!"
-
+      uses: miguelteixeiraa/action-run-in-background@v1
+      with:
+        script: |
+          npm run turn-on-api &
+        readiness-script: |
+          # Wait for the server to start
+          echo "Waiting for server to start..."
+          sleep 5
+          curl -f http://localhost:3000 || { echo "Server failed to start!"; exit 1; }
+          echo "Server is up and running!"
     - name: Create results directory
       run: mkdir -p ./testResults
 
